routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => ['auth'] 
], function() {
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::get('/servicos-de-emissao', 'ServicosController@index')->name('admin.servicos');

    Route::post('/despachantes/habilitar/{id}', 'DespachantesController@enable');
    Route::post('/despachantes/desabilitar/{id}', 'DespachantesController@disable');

    Route::resource('despachantes', 'DespachantesController');
    Route::resource('usuarios', 'UsuariosController');
});

Route::group(['prefix' => 'endpoints', 'namespace' => 'Api'], function() {
    Route::get('despachantes/{id}', 'Admin\DespachantesApiController@show')->name('api.despachantes.show');
});

/**
 * Rotas Administrativas do Cliente
 */
Route::group([
    'prefix' => 'cliente',
    'namespace' => 'Cliente',
    'middleware' => ['auth'] 
], function() {
    Route::get('/', 'PainelController@index')->name('clientes.painel');
    Route::post('/requisitar-servico', 'RequisitarServicosController@store')->name('servicos.store');
    Route::post('/consultar-debitos', 'ConsultarDebitosController@consultar')->name('cliente.consultar-debitos');
    Route::post('/anexar-arquivo', 'AnexarArquivosController@store')->name('cliente.anexar-arquivo.store');
    Route::get('/download/{arquivo}', 'AnexarArquivosController@download')->name('cliente.download-arquivo');
});

/**
 * Rotas Administrativas do Despachante
 */
Route::group([
    'prefix' => 'despachante',
    'namespace' => 'Despachante',
    'middleware' => ['auth', 'logout.despachante.sem.acesso'] 
], function() {
    Route::get('/', 'PainelController@index')->name('despachantes.painel');
    Route::post('/alterar-situacao-do-servico', 'ServicosController@alterarStatus')->name('despachantes.servico.alterar-status');
});

/**
 * Demais Rotas
 */
Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::get('/painel', 'HomeController@painel')->name('redirecionar.painel');
Route::post('/consultar-debitos', 'HomeController@consultarDebitos')->name('consultar-debitos');

app/Http/Controllers/Admin/UsuariosController.php
<?php

namespace Emplaque\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Emplaque\Http\Controllers\Controller;

use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;

use Emplaque\Repositories\Interfaces\UsuarioRepository;
use Emplaque\Validators\UsuarioValidator;

class UsuariosController extends Controller
{
    protected $repository;
    protected $validator;

    public function __construct(UsuarioRepository $repository, UsuarioValidator $validator) 
    {
        $this->middleware(['role:administrador']);

        $this->repository = $repository;
        $this->validator = $validator;
    }

    public function index(Request $request)
    {
        $usuarios = $this->repository->all();

        if ( $request->has('clientes') ) {
            $aux = [];
            foreach( $usuarios as $usuario ) {
                if( $usuario->hasRole('cliente') ) {
                    $aux[] = $usuario;
                }
            }

            $usuarios = $aux;
        }

        return view('admin.usuarios.index', compact('usuarios'));
    }

    /**
     * Retorna dados via json
     */
    public function show($id)
    {

    }

    public function create()
    {
        return view('admin.usuarios.adicionar');
    }

    public function store(Request $request)
    {
        try {
            $this->validator
                ->with($request->all())
                ->passesOrFail(ValidatorInterface::RULE_CREATE);

            $inputs = $request->all();
            $inputs['password'] = bcrypt( trim($inputs['password']) );

            $usuario = $this->repository->create($inputs);

            /**
             * TODO: Refatorar esse trecho e incluir lá no repositório
             * Acertando tipo do usuario
             */
            $usuario->assignRole($inputs['tipo']);

            $retorno = [
                'mensagem' => "Usuário adicionado com sucesso",
                'data'    => $usuario,
            ];
     
            return redirect()->route('usuarios.index')->with('success', $retorno['mensagem']);
        } catch (ValidatorException $e) {
            return redirect()
                    ->route('usuarios.index')
                    ->withErrors($e->getMessageBag())
                    ->withInput();
        }
    }

    public function edit($id)
    {
        $usuario = $this->repository->find($id);
        return view('admin.usuarios.editar', compact('usuario'));
    }

    public function update(Request $request, $id)
    {
        try {
            $this->validator
                ->with($request->all())
                ->passesOrFail(ValidatorInterface::RULE_UPDATE);

            $inputs = $request->all();

            if ( $request->has('password') ) 
                $inputs['password'] = bcrypt( trim($inputs['password']) );

            if ( $request->has('tipo') ) 
                $usuario = $this->repository->update($inputs, $id);

            /**
             * TODO: Refatorar esse trecho e incluir lá no repositório
             * Acertando tipo do usuario
             */
            $usuario->syncRoles([$inputs['tipo']]);

            $retorno = [
                'mensagem' => "Usuário atualizado com sucesso",
                'data'    => $usuario,
            ];
     
            return redirect()->route('usuarios.index')->with('success', $retorno['mensagem']);
        } catch (ValidatorException $e) {
            return redirect()
                    ->route('usuarios.index')
                    ->withErrors($e->getMessageBag())
                    ->withInput();
        }
    }

    public function destroy($id)
    {
        $usuario = $this->repository->find( $id );
        if ( !$usuario->hasRole('despachante')) {
            $usuario->delete();
            return redirect()->route('usuarios.index')->with('success', 'Usuário deletado da base de dados com sucesso.');
        } else {
            return redirect()->route('usuarios.index')->with('danger', 'Ocorreu algum problema na requisição. Usuário pode está associado à um Despachante.');
        }
    }
}

resources/views/admin/usuarios/adicionar.blade.php
@extends('adminlte::page')

@section('content')
    <div class="box box-solid">
        <div class="box-header">
            <h3 class="box-title">Formulário de cadastro de usuario</h3>
        </div>
        <div class="box-body">
            <form action="{{ route('usuarios.store') }}" method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="row">
                    <div class="form-group col-sm-3">
                        <label for="name">Nome do usuário</label>
                        <input type="text" 
                               class="form-control obrigatorio" 
                               placeholder="Name do usuário"
                               name="name"
                               required>
                    </div>

                    <div class="form-group col-sm-3">
                        <label for="email">Email</label>
                        <input type="email" 
                               id="email" 
                               class="form-control obrigatorio" 
                               placeholder="usuario@email.com.br"
                               name="email"
                               required>
                    </div>

                    <div class="form-group col-sm-3">
                        <label for="password">Senha</label>
                        <input type="password" 
                               id="password" 
                               class="form-control obrigatorio" 
                               name="password"
                               required>
                    </div>

                    <div class="form-group col-sm-3">
                        <label for="tipo">Status</label>
                        <select id="tipo" class="form-control" name="tipo" required>
                            <option value="administrador" selected>Administrador</option>
                            <option value="despachante">Despachante</option>
                        </select>
                    </div>
                </div>

                <div class="text-right">
                    <button type="button" class="btn btn-danger"
                        onclick="javascript:history.back()"
                    >
                        <i class="fa fa-fw fa-close"></i>
                        Cancelar
                    </button>

                    <button type="submit" class="btn btn-success">
                        <i class="fa fa-fw fa-check"></i>
                        Adicionar usuario
                    </button>
                </div>
            </form>
        </div>
    </div>
@stop

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js" integrity="sha256-u7MY6EG5ass8JhTuxBek18r5YG6pllB9zLqE4vZyTn4=" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            $('select.form-control').select2();
        });
    </script>
@stop

resources/views/admin/usuarios/editar.blade.php
@extends('adminlte::page')

@section('content')
    <div class="box box-solid">
        <div class="box-header">
            <h3 class="box-title">Formulário de cadastro de usuario</h3>
        </div>
        <div class="box-body">
            <form action="{{ route('usuarios.update', ['id' => $usuario->id]) }}" method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="row">
                    <div class="form-group col-sm-3">
                        <label for="name">Nome do usuário</label>
                        <input type="text" 
                               class="form-control obrigatorio" 
                               placeholder="Name do usuário"
                               name="name"
                               value="{{ $usuario->name }}"
                        >
                    </div>

                    <div class="form-group col-sm-3">
                        <label for="email">Email</label>
                        <input type="email" 
                               id="email" 
                               class="form-control obrigatorio" 
                               placeholder="usuario@email.com.br"
                               name="email"
                               value="{{ $usuario->email }}"
                        >
                    </div>

                    <div class="form-group col-sm-3">
                        <label for="password">Senha</label>
                        <input type="password" 
                               id="password" 
                               class="form-control obrigatorio" 
                               name="password"
                        >
                    </div>

                    <div class="form-group col-sm-3">
                        <label for="tipo">Status</label>
                        <select id="tipo" class="form-control" name="tipo" @if( $usuario->hasRole('cliente')) disabled @endif>
                            <option value="administrador" @if( $usuario->hasrole('administrador')) selected @endif>Administrador</option>
                            <option value="despachante" @if( $usuario->hasRole('despachante')) selected @endif>Despachante</option>
                            <option value="cliente" @if( $usuario->hasRole('cliente')) selected @endif>Cliente</option>
                        </select>
                    </div>
                </div>

                <div class="text-right">
                    <button type="button" class="btn btn-danger"
                        onclick="javascript:history.back()"
                    >
                        <i class="fa fa-fw fa-close"></i>
                        Cancelar
                    </button>

                    <button type="submit" class="btn btn-success">
                        <i class="fa fa-fw fa-check"></i>
                        Editar usuario
                    </button>
                </div>
            </form>
        </div>
    </div>
@stop

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js" integrity="sha256-u7MY6EG5ass8JhTuxBek18r5YG6pllB9zLqE4vZyTn4=" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            $('select.form-control').select2();
        });
    </script>
@stop

resources/views/admin/usuarios/index.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="box box-solid">
                <div class="box-header">
                    <h3 class="box-title">
                        Listagem de Usuários
                    </h3>
                    <a role="button" 
                        class="btn btn-primary"
                        href="{{ route('usuarios.create') }}"
                    >
                        <i class="fa fa-fw fa-plus"></i>
                        Adicionar novo usuário
                    </a>
                </div>
                <div class="box-body">        
                    <table id="tabela-usuarios" class="table table-bordered table-condensed">
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Email</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ( $usuarios as $usuario )
                            <tr>
                                <td>
                                    {{ $usuario->name }} &nbsp;
                                    @if ( count($usuario->getRoleNames()) )
                                        <span class="label label-default">{{ $usuario->getRoleNames()[0]}}</span>
                                    @endif
                                </td>
                                <td>{{ $usuario->email }}</td>
                                <td class="text-right">
                                    <a role="button" 
                                        class="btn btn-xs btn-warning"
                                        href="{{ route('usuarios.edit', ['id' => $usuario->id]) }}"
                                    >
                                        <i class="fa fa-fw fa-edit"></i>
                                        editar
                                    </a>
                                    <button type="button" 
                                            class="btn btn-xs btn-danger"
                                            onclick="deletarUsuario({{$usuario->id}})">
                                        <i class="fa fa-fw fa-trash"></i>
                                        apagar
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="box box-solid">
                <div class="box-body">
                    <ul class="nav nav-pills">
                        <li role="presentation">
                            <span class="label label-warning">
                                <i class="fa fa-fw fa-clock-o"></i>
                            </span> &nbsp; Aguardando aprovação &nbsp;
                        </li>
                        <li role="presentation">
                            <span class="label label-success">
                                <i class="fa fa-fw fa-check"></i>
                            </span> &nbsp; Aprovado &nbsp;
                        </li>
                        <li role="presentation">
                            <span class="label label-danger">
                                <i class="fa fa-fw fa-close"></i>
                            </span> &nbsp; Negado &nbsp;
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    @include('admin.usuarios.includes.form-deletar-usuario')
@stop