routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => ['auth'] 
], function() {
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::get('/servicos-de-emissao', 'ServicosController@index')->name('admin.servicos');

    Route::post('/despachantes/habilitar/{id}', 'DespachantesController@enable');
    Route::post('/despachantes/desabilitar/{id}', 'DespachantesController@disable');

    Route::resource('despachantes', 'DespachantesController');
    Route::resource('usuarios', 'UsuariosController');
});

Route::group(['prefix' => 'endpoints', 'namespace' => 'Api'], function() {
    Route::get('despachantes/{id}', 'Admin\DespachantesApiController@show')->name('api.despachantes.show');
});

/**
 * Rotas Administrativas do Cliente
 */
Route::group([
    'prefix' => 'cliente',
    'namespace' => 'Cliente',
    'middleware' => ['auth'] 
], function() {
    Route::get('/', 'PainelController@index')->name('clientes.painel');
    Route::post('/requisitar-servico', 'RequisitarServicosController@store')->name('servicos.store');
    Route::post('/consultar-debitos', 'ConsultarDebitosController@consultar')->name('cliente.consultar-debitos');
    Route::post('/anexar-arquivo', 'AnexarArquivosController@store')->name('cliente.anexar-arquivo.store');
    Route::get('/download/{arquivo}', 'AnexarArquivosController@download')->name('cliente.download-arquivo');
});

/**
 * Rotas Administrativas do Despachante
 */
Route::group([
    'prefix' => 'despachante',
    'namespace' => 'Despachante',
    'middleware' => ['auth', 'logout.despachante.sem.acesso'] 
], function() {
    Route::get('/', 'PainelController@index')->name('despachantes.painel');
    Route::post('/alterar-situacao-do-servico', 'ServicosController@alterarStatus')->name('despachantes.servico.alterar-status');
});

/**
 * Demais Rotas
 */
Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::get('/painel', 'HomeController@painel')->name('redirecionar.painel');
Route::post('/consultar-debitos', 'HomeController@consultarDebitos')->name('consultar-debitos');

resources/views/admin/dashboard.blade.php
@extends('adminlte::page') @section('content')

<div class="row">
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>{{ $total_clientes}}</h3>

                <p>Clientes</p>
            </div>
            <div class="icon">
                <i class="fa fa-users"></i>
            </div>
            <a href="/admin/usuarios/?clientes" class="small-box-footer">Informações
                <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
            <div class="inner">
                <h3>{{ $total_despachantes}}</h3>

                <p>Despachantes</p>
            </div>
            <div class="icon">
                <i class="fa fa-address-card-o"></i>
            </div>
            <a href="{{ route('despachantes.index') }}" class="small-box-footer">Informações
                <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3>{{ $total_servicos_em_aberto }}</h3>

                <p>Serviços em Aberto</p>
            </div>
            <div class="icon">
                <i class="fa fa-hourglass-1"></i>
            </div>
                <a href="{{ route('admin.servicos') }}" class="small-box-footer">Informações
                <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-red">
            <div class="inner">
                <h3>{{ $total_servicos_realizados}}</h3>

                <p>Serviços Realizados</p>
            </div>
            <div class="icon">
                <i class="fa fa-check-square-o"></i>
            </div>
            <a href="{{ route('admin.servicos') }}" class="small-box-footer">Informações
                <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-purple">
            <div class="inner">
                <h3>{{ $novos_despachantes }}</h3>

                <p>Novos Despachantes</p>
            </div>
            <div class="icon">
                <i class="fa fa-address-card-o"></i>
            </div>
            <a href="{{ route('despachantes.index') }}" class="small-box-footer">Informações
                <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div>
</div>
@endsection