routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => ['auth'] 
], function() {
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::get('/servicos-de-emissao', 'ServicosController@index')->name('admin.servicos');

    Route::post('/despachantes/habilitar/{id}', 'DespachantesController@enable');
    Route::post('/despachantes/desabilitar/{id}', 'DespachantesController@disable');

    Route::resource('despachantes', 'DespachantesController');
    Route::resource('usuarios', 'UsuariosController');
});

Route::group(['prefix' => 'endpoints', 'namespace' => 'Api'], function() {
    Route::get('despachantes/{id}', 'Admin\DespachantesApiController@show')->name('api.despachantes.show');
});

/**
 * Rotas Administrativas do Cliente
 */
Route::group([
    'prefix' => 'cliente',
    'namespace' => 'Cliente',
    'middleware' => ['auth'] 
], function() {
    Route::get('/', 'PainelController@index')->name('clientes.painel');
    Route::post('/requisitar-servico', 'RequisitarServicosController@store')->name('servicos.store');
    Route::post('/consultar-debitos', 'ConsultarDebitosController@consultar')->name('cliente.consultar-debitos');
    Route::post('/anexar-arquivo', 'AnexarArquivosController@store')->name('cliente.anexar-arquivo.store');
    Route::get('/download/{arquivo}', 'AnexarArquivosController@download')->name('cliente.download-arquivo');
});

/**
 * Rotas Administrativas do Despachante
 */
Route::group([
    'prefix' => 'despachante',
    'namespace' => 'Despachante',
    'middleware' => ['auth', 'logout.despachante.sem.acesso'] 
], function() {
    Route::get('/', 'PainelController@index')->name('despachantes.painel');
    Route::post('/alterar-situacao-do-servico', 'ServicosController@alterarStatus')->name('despachantes.servico.alterar-status');
});

/**
 * Demais Rotas
 */
Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::get('/painel', 'HomeController@painel')->name('redirecionar.painel');
Route::post('/consultar-debitos', 'HomeController@consultarDebitos')->name('consultar-debitos');

app/Models/Despachante.php
<?php

namespace Emplaque\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class Despachante.
 *
 * @package namespace Emplaque\Models;
 */
class Despachante extends Model implements Transformable
{
    use TransformableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nome',
        'logo',
        'status',
        'email',
        'telefone',
        'celular',
        'municipio_codigo',
        'endereco'
    ];

    public function usuario()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function servicos()
    {
        return $this->hasMany(Servico::class, 'despachante_id');
    }

    public function municipio()
    {
        return $this->belongsTo(Municipio::class, 'municipio_codigo', 'Codigo');
    }

}

app/Http/Controllers/Admin/DespachantesController.php
<?php

namespace Emplaque\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Emplaque\Http\Controllers\Controller;

use Illuminate\Support\Facades\Storage;

use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;

use Emplaque\Repositories\Interfaces\DespachanteRepository;
use Emplaque\Validators\DespachanteValidator;

use Emplaque\Repositories\Interfaces\UsuarioRepository;
use Emplaque\Validators\UsuarioValidator;

use Emplaque\Repositories\Interfaces\MunicipioRepository;


class DespachantesController extends Controller
{
    protected $repository;
    protected $validator;
    protected $usuarioRepository;
    protected $municipioRepository;

    public function __construct(
        DespachanteRepository $repository, 
        DespachanteValidator $validator, 
        UsuarioRepository $usuarioRepository, 
        MunicipioRepository $municipioRepository
    )
    {
        $this->middleware(['role:administrador']);

        $this->repository = $repository;
        $this->validator = $validator;
        $this->usuarioRepository = $usuarioRepository;
        $this->municipioRepository = $municipioRepository;
    }

    public function index()
    {
        $despachantes = $this->repository->all();
        return view('admin.despachantes.index', compact('despachantes'));
    }

    public function create()
    {
        $municipios = $this->municipioRepository->findWhere( ['Uf' => 'SC'] );
        return view('admin.despachantes.adicionar', compact('municipios'));
    }

    public function store(Request $request)
    {
        try {
            $this->validator
                ->with($request->all())
                ->passesOrFail(ValidatorInterface::RULE_CREATE);

            $inputs = $request->all();

            /* Salvando e obtendo url da foto salva */
            if ( $request->has('logo') && $request->file('logo')->isValid() ){
                $inputs['logo'] = $this->repository->upload( $request->file('logo') );
            }

            $despachante = $this->repository->create($inputs);

            $retorno = [
                'mensagem' => "Despachante adicionado com sucesso",
                'data'    => $despachante,
            ];
     
            return redirect()->route('despachantes.index')->with('success', $retorno['mensagem']);
        } catch (ValidatorException $e) {
            return redirect()
                    ->route('despachantes.index')
                    ->withErrors($e->getMessageBag())
                    ->withInput();
        }
    }

    public function edit($id)
    {
        $despachante = $this->repository->find( $id );
        $municipios = $this->municipioRepository->findWhere( ['Uf' => 'SC'] );
        return view('admin.despachantes.editar', compact('despachante', 'municipios'));
    }

    public function update(Request $request, $id)   
    {
        try {
            $this->validator
                ->with($request->all())
                ->passesOrFail(ValidatorInterface::RULE_UPDATE);

            $inputs = $request->all();

            $despachante = $this->repository->find( $id );

            /* Salvando/Atualizando e obtendo url da foto salva */
            if ( $request->has('logo') && $request->file('logo')->isValid() ){

                /** apagando arquivo anterior */
                Storage::disk('public')->delete( $despachante->logo );
                
                /** salvando novo arquivo */
                $inputs['logo'] = $this->repository->upload( $request->file('logo') );
            }

            $despachante = $this->repository->update($inputs, $id);

            $retorno = [
                'mensagem' => "Despachante atualizado com sucesso",
                'data'    => $despachante,
            ];
     
            return redirect()->route('despachantes.index')->with('success', $retorno['mensagem']);
        } catch (ValidatorException $e) {
            return redirect()
                    ->route('despachantes.index')
                    ->withErrors($e->getMessageBag())
                    ->withInput();
        }
    }

    public function destroy($id)
    {
        $despachante = $this->repository->find( $id );
        if ( $despachante ) 
        {
            /** apagando arquivo */
            Storage::disk('public')->delete( $despachante->logo );
            
            $despachante->delete();
            return redirect()->route('despachantes.index')->with('success', 'Despachante deletado da base de dados com sucesso.');
        } else {
            return redirect()->route('despachantes.index')->with('danger', 'Ocorreu um erro no processamento da requisição. Tente novamente em alguns instantes.');
        }
    }

    public function enable($id)
    {
        $despachante = $this->repository->find( $id );

        if ( $despachante && !$despachante->user_id )
        {
            $data = [
                'name' => $despachante->nome,
                'email' => trim($despachante->email),
                'password' => bcrypt(trim($despachante->email))
            ];

            try {
                $this->validator
                ->with($data)
                ->passesOrFail(ValidatorInterface::RULE_CREATE);
    
                $usuario = $this->usuarioRepository->create( $data );

                /** associando despachante ao usuário */
                $despachante->user_id = $usuario->id;
                $despachante->status = 'APROVADO';
                
                $usuario->syncRoles(['despachante']);

                $despachante->save();
                $usuario->save();
    
                $retorno = [
                    'mensagem' => "Despachante habilitado com sucesso",
                    'data'    => $despachante,
                ];
         
                return redirect()->route('despachantes.index')->with('success', $retorno['mensagem']);
            } catch (ValidatorException $e) {
                return redirect()
                        ->route('despachantes.index')
                        ->withErrors($e->getMessageBag())
                        ->withInput();
            } 
        } elseif ( $despachante && $despachante->user_id ) {

            $despachante->status = 'APROVADO';
            $despachante->save();
            $retorno = [
                'mensagem' => "Despachante habilitado com sucesso",
                'data'    => $despachante,
            ];
     
            return redirect()->route('despachantes.index')->with('success', $retorno['mensagem']);
        } else {
            return redirect()->route('despachantes.index');
        }
    }

    public function disable($id)
    {
        $despachante = $this->repository->find( $id );

        if ( $despachante )
        {
            $despachante->status = "NEGADO";
            $despachante->save();

            $retorno = [
                'mensagem' => "Despachante desabilitado sucesso",
                'data'    => $despachante,
            ];
     
            return redirect()->route('despachantes.index')->with('success', $retorno['mensagem']);
        } else {
            return redirect()->route('despachantes.index');
        }
    }
}

app/Http/Controllers/Despachante/PainelController.php
<?php

namespace Emplaque\Http\Controllers\Despachante;

use Auth;

use Illuminate\Http\Request;
use Emplaque\Http\Controllers\Controller;

use Emplaque\Repositories\Interfaces\ServicoRepository;

class PainelController extends Controller
{
    protected $servicoRepo;

    public function __construct(ServicoRepository $servicoRepo)
    {
        $this->middleware(['role:despachante']);

        $this->servicoRepo = $servicoRepo;
    }

    public function index()
    {
        $servicos = $this->servicoRepo->findWhere([
                        'despachante_id' => Auth::user()->despachante->id,
                        ['status', '!=', 'FINALIZADO' ]
                    ]);
        return view('despachante.painel', compact('servicos'));
    }
}

app/Http/Controllers/Despachante/ServicosController.php
<?php

namespace Emplaque\Http\Controllers\Despachante;

use Illuminate\Http\Request;
use Emplaque\Http\Controllers\Controller;
use Emplaque\Repositories\Interfaces\ServicoRepository;

class ServicosController extends Controller
{
    protected $servicoRepo;

    public function __construct(ServicoRepository $servicoRepo)
    {
        $this->servicoRepo = $servicoRepo;
    }

    public function alterarStatus(Request $request)
    {
        $servico = $this->servicoRepo->find( $request->input('servico_id') );
        if ( $servico )
        {
            $servico->status = $request->input('status');
            $servico->save();
            $retorno = [
                'mensagem' => "Situação do serviço alterada com sucesso. Um email foi enviado alertando o cliente dessa alteração.",
                'data'    => $servico,
            ];
     
            /** 
             * TODO: Enviar email alertando cliente sobre alteração do status  
             */

            return redirect()->route('despachantes.painel')->with('success', $retorno['mensagem']);
        } else {
            return response( 404 );
        }
    }
}

resources/views/admin/despachantes/adicionar.blade.php
@extends('adminlte::page')

@section('content')
    <div class="box box-solid">
        <div class="box-header">
            <h3 class="box-title">Formulário de cadastro de despachante</h3>
        </div>
        <div class="box-body">
            <form action="{{ route('despachantes.store') }}" method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="row">
                    <div class="form-group col-sm-5">
                        <label for="nome">Nome do Despachante</label>
                        <input type="text" 
                               class="form-control obrigatorio" 
                               placeholder="Nome/Razão Social do Despachante"
                               name="nome"
                               required>
                    </div>

                    <div class="form-group col-sm-4">
                        <label for="email">Email</label>
                        <input type="email" 
                               id="email" 
                               class="form-control obrigatorio" 
                               placeholder="despachante@email.com.br"
                               name="email"
                               required>
                    </div>

                    <div class="form-group col-sm-3">
                        <label for="status">Status</label>
                        <select id="status" class="form-control" name="status" required>
                            <option value="AGUARDANDO APROVACAO" selected>Aguardando Aprovação</option>
                            <option value="APROVADO">Aprovado</option>
                            <option value="NEGADO">Negado</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-sm-2">
                        <label for="telefone">Tel. Residencial</label>
                        <input type="text" 
                               id="telefone" 
                               class="form-control obrigatorio" 
                               data-mask="(00) 0000-0000"
                               name="telefone"
                               required>
                    </div>

                    <div class="form-group col-sm-2">
                        <label for="celular">Tel. Celular</label>
                        <input type="text" 
                               id="celular" 
                               class="form-control obrigatorio" 
                               data-mask="(00) 00000-0000"
                               name="celular"
                               required>
                    </div>

                    <div class="form-group col-sm-3">
                        <label for="municipio">Município</label>
                        <select id="municipio" class="form-control" name="municipio_codigo">
                            @foreach( $municipios as $municipio )
                                <option value="{{ $municipio->Codigo }}" required>{{ $municipio->Nome }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group col-sm-5">
                        <label for="endereco">Endereço</label>
                        <input type="text" 
                               id="endereco" 
                               class="form-control obrigatorio" 
                               name="endereco"
                               required>
                    </div>
                </div>

                 <div class="form-group">
                    <label for="logotipo-despachante">Logotipo</label>
                    <input type="file" id="logotipo-despachante" name="logo">
                    <p class="help-block">Escolha o logotipo do despachante em .JPG ou PNG</p>
                </div>

                <div class="text-right">
                    <a role="button" class="btn btn-danger"
                        href="{{ route('despachantes.index') }}"
                    >
                        <i class="fa fa-fw fa-close"></i>
                        Cancelar
                    </a>

                    <button type="submit" class="btn btn-success">
                        <i class="fa fa-fw fa-check"></i>
                        Adicionar despachante
                    </button>
                </div>
            </form>
        </div>
    </div>
@stop

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js" integrity="sha256-u7MY6EG5ass8JhTuxBek18r5YG6pllB9zLqE4vZyTn4=" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            $('select.form-control').select2();
        });
    </script>
@stop

resources/views/admin/despachantes/editar.blade.php
@extends('adminlte::page')

@section('content')
    <div class="box box-solid">
        <div class="box-header">
            <h3 class="box-title">Formulário de cadastro de despachante</h3>
        </div>
        <div class="box-body">
            <form action="{{ route('despachantes.update', ['id' => $despachante->id ]) }}" method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="row">
                    <div class="form-group col-sm-5">
                        <label for="nome">Nome do Despachante</label>
                        <input type="text" 
                               class="form-control obrigatorio" 
                               placeholder="Nome/Razão Social do Despachante"
                               name="nome"
                               value="{{ $despachante->nome }}"
                               >
                    </div>

                    <div class="form-group col-sm-4">
                        <label for="email">Email</label>
                        <input type="email" 
                               id="email" 
                               class="form-control obrigatorio" 
                               placeholder="despachante@email.com.br"
                               name="email"
                               value="{{ $despachante->email }}"
                               >
                    </div>

                    <div class="form-group col-sm-3">
                        <label for="status">Status</label>
                        <select id="status" class="form-control" name="status" >
                            <option value="AGUARDANDO APROVACAO" @if( $despachante->status === 'AGUARDANDO APROVACAO') selected @endif>Aguardando Aprovação</option>
                            <option value="APROVADO" @if( $despachante->status === 'APROVADO') selected @endif>Aprovado</option>
                            <option value="NEGADO" @if( $despachante->status === 'NEGADO') selected @endif>Negado</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-sm-2">
                        <label for="telefone">Tel. Residencial</label>
                        <input type="text" 
                               id="telefone" 
                               class="form-control obrigatorio" 
                               data-mask="(00) 0000-0000"
                               name="telefone"
                               value="{{ $despachante->telefone }}"
                               >
                    </div>

                    <div class="form-group col-sm-2">
                        <label for="celular">Tel. Celular</label>
                        <input type="text" 
                               id="celular" 
                               class="form-control obrigatorio" 
                               data-mask="(00) 00000-0000"
                               name="celular"
                               value="{{ $despachante->celular }}"
                               >
                    </div>

                    <div class="form-group col-sm-3">
                        <label for="municipio">Município</label>
                        <select id="municipio" class="form-control" name="municipio_codigo">
                            @foreach( $municipios as $municipio )
                                <option value="{{ $municipio->Codigo }}" @if( $municipio->Codigo === $despachante->municipio_codigo) selected @endif>{{ $municipio->Nome }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group col-sm-5">
                        <label for="endereco">Endereço</label>
                        <input type="text" 
                               id="endereco" 
                               class="form-control obrigatorio" 
                               name="endereco"
                               value="{{ $despachante->endereco }}"
                               >
                    </div>
                </div>

                 <div class="form-group">
                    <label for="logotipo-despachante">Logotipo</label>
                    <input type="file" id="logotipo-despachante" name="logo">
                    <p class="help-block">Escolha o logotipo do despachante em .JPG ou PNG</p>
                </div>

                <div class="text-right">
                    <a role="button" class="btn btn-danger"
                        href="{{ route('despachantes.index') }}"
                    >
                        <i class="fa fa-fw fa-close"></i>
                        Cancelar
                    </a>

                    <button type="submit" class="btn btn-success">
                        <i class="fa fa-fw fa-check"></i>
                        Atualizar despachante
                    </button>
                </div>
            </form>
        </div>
    </div>
@stop

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js" integrity="sha256-u7MY6EG5ass8JhTuxBek18r5YG6pllB9zLqE4vZyTn4=" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            $('select.form-control').select2();
        });
    </script>
@stop

resources/views/admin/despachantes/index.blade.php
@extends('adminlte::page') 

@section('content')
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="box box-solid">
                <div class="box-header">
                    <h3 class="box-title">
                        Listagem de Despachantes
                    </h3>
                    <a role="button" 
                        class="btn btn-primary"
                        href="{{ route('despachantes.create') }}"
                    >
                        <i class="fa fa-fw fa-plus"></i>
                        Adicionar novo despachante
                    </a>
                </div>
                <div class="box-body">        
                    <table id="tabela-despachantes" class="table table-bordered table-condensed">
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Telefone</th>
                                <th>Celular</th>
                                <th>Email</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ( $despachantes as $despachante )
                            <tr>
                                <td>
                                    @if ( $despachante->status === 'AGUARDANDO APROVACAO' )
                                        <span class="label label-warning"><i class="fa fa-fw fa-clock-o"></i></span> &nbsp;
                                    @elseif( $despachante->status === 'APROVADO' )
                                        <span class="label label-success"><i class="fa fa-fw fa-check"></i></span> &nbsp;
                                    @elseif( $despachante->status === 'NEGADO')
                                        <span class="label label-danger"><i class="fa fa-fw fa-close"></i></span> &nbsp;
                                    @endif 
                                    {{ $despachante->nome }}
                                </td>
                                <td>{{ $despachante->telefone }}</td>
                                <td>{{ $despachante->celular }}</td>
                                <td>{{ $despachante->email }}</td>
                                <td class="text-right">
                                    @if( $despachante->status === 'AGUARDANDO APROVACAO' )
                                        <button type="button" 
                                            id="btn-habilitar-despachante-{{ $despachante->id }}"
                                            class="btn btn-xs btn-success"
                                            onclick="habilitarDespachante({{ $despachante->id }})"      
                                            >
                                                <i class="fa fa-fw fa-check"></i>
                                                habilitar acesso
                                        </button>
                                        <button type="button" 
                                            id="btn-desabilitar-despachante-{{ $despachante->id }}"
                                            class="btn btn-xs btn-danger" 
                                            onclick="desabilitarDespachante({{ $despachante->id }})"      
                                            >
                                                <i class="fa fa-fw fa-exclamation-circle"></i>
                                                negar acesso
                                        </button>
                                    @elseif( $despachante->status === 'APROVADO' )
                                        <button type="button" 
                                            id="btn-desabilitar-despachante-{{ $despachante->id }}"
                                            class="btn btn-xs btn-danger" 
                                            onclick="desabilitarDespachante({{ $despachante->id }})"      
                                            >
                                                <i class="fa fa-fw fa-exclamation-circle"></i>
                                                negar acesso
                                        </button>

                                    @elseif( $despachante->status === 'NEGADO' )
                                        <button type="button" 
                                            id="btn-habilitar-despachante-{{ $despachante->id }}"
                                            class="btn btn-xs btn-success"
                                            data-loading-text='<i class="fa fa-fw fa-spinner"></i> carregando...'  
                                            onclick="habilitarDespachante({{ $despachante->id }})"      
                                            >
                                                <i class="fa fa-fw fa-check"></i>
                                                habilitar acesso
                                        </button>
                                    @endif
                                    <button type="button" 
                                            id="btn-exibir-despachante-{{ $despachante->id }}"
                                            class="btn btn-xs btn-primary"
                                            data-loading-text='<i class="fa fa-fw fa-spinner"></i> carregando...'  
                                            onclick="exibirDespachante({{ $despachante->id }})"      
                                    >
                                        <i class="fa fa-fw fa-address-card"></i>
                                        visualizar
                                    </button>
                                    <a role="button" 
                                        class="btn btn-xs btn-warning"
                                        href="{{ route('despachantes.edit', ['id' => $despachante->id ]) }}"
                                    >
                                        <i class="fa fa-fw fa-edit"></i>
                                        editar
                                    </a>
                                    <button type="button" 
                                            class="btn btn-xs btn-danger"
                                            onclick="deletarDespachante({{ $despachante->id }})">
                                        <i class="fa fa-fw fa-trash"></i>
                                        apagar
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="box box-solid">
                <div class="box-body">
                    <ul class="nav nav-pills">
                        <li role="presentation">
                            <span class="label label-warning">
                                <i class="fa fa-fw fa-clock-o"></i>
                            </span> &nbsp; Aguardando aprovação &nbsp;
                        </li>
                        <li role="presentation">
                            <span class="label label-success">
                                <i class="fa fa-fw fa-check"></i>
                            </span> &nbsp; Aprovado &nbsp;
                        </li>
                        <li role="presentation">
                            <span class="label label-danger">
                                <i class="fa fa-fw fa-close"></i>
                            </span> &nbsp; Negado &nbsp;
                        </li>
                    </ul>
                </div>
            </div>

        </div>
    </div>

    @include('admin.despachantes.includes.form-deletar-despachante')
    @include('admin.despachantes.includes.modal-exibir-despachante')
@endsection 